version: "3"

includes:
  docs: "docs/tasks.yml"
  utils: "tools/yscope-dev-utils/taskfiles/utils.yml"

vars:
  # Build paths
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"

tasks:
  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
