name: "lint"

on:
  pull_request:
    types: ["opened", "reopened"]
  push:
  schedule:
    # Run at midnight UTC every day with 15 minutes delay added to avoid high load periods
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions:
  # So the workflow can cancel in-progress jobs
  actions: "write"

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: "ubuntu-latest"
    permissions:
      # So `eslint-annotate-action` can create / update status checks
      checks: "write"
      # So `eslint-annotate-action` can get pull request files
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
      - run: "npm --prefix new-log-viewer/ clean-install"

      - name: "Register Stylelint problem matcher"
        run: "echo '::add-matcher::./.github/problem-matchers/stylelint.json'"
      # TODO: remove below `sed` hack once the new-log-viewer sources are moved to the project's root.
      - run: |
          npm --prefix new-log-viewer/ run lint:css-check 2>&1 | sed 's#src/#new-log-viewer/src/#g'
          exit ${PIPESTATUS[0]}
      - name: "Remove Stylelint problem matcher"
        if: "always()"
        run: "echo '::remove-matcher owner=stylelint::'"

      - run: "npm --prefix new-log-viewer/ run lint:js-ci"
        if: "always()"
      - uses: "ataylorme/eslint-annotate-action@v3"
        if: "always()"
        with:
          fail-on-error: true
          fail-on-warning: true
          only-pr-files: true
          report-json: "./new-log-viewer/eslint-report.json"
