name: "lint"

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
  schedule:
    # Run at midnight UTC every day with 15 minutes delay added to avoid high load periods
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions:
  # So the workflow can cancel in-progress jobs
  actions: "write"

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
      - run: "npm clean-install"
      - name: "Set up Stylelint Problem Matcher"
        run: "echo '::add-matcher::./.github/problem-matchers/stylelint.json'"
      - name: "Run `lint:ci` script."
        run: |-
          # Disable ANSI color codes in Stylelint default "string" formatter
          export NO_COLOR=1
          npm run lint:ci
      - if: "always()"
        name: "Remove Stylelint Problem Matcher"
        run: "echo '::remove-matcher::./.github/problem-matchers/stylelint.json'"
