name: "lint"

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
  push:
  schedule:
    # Run at midnight UTC every day with 15 minutes delay added to avoid high load periods
    - cron: "15 0 * * *"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  # Cancel in-progress jobs for efficiency
  cancel-in-progress: true

jobs:
  lint-check:
    runs-on: "ubuntu-latest"
    permissions:
      actions: "write"
      checks: "write"
      contents: "read"
      pull-requests: "read"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "recursive"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
      - run: "npm --prefix new-log-viewer/ clean-install"

      - run: "npm --prefix new-log-viewer/ run lint:js-ci"
        continue-on-error: true
      - uses: "ataylorme/eslint-annotate-action@v3"
        with:
          fail-on-error: true
          fail-on-warning: true
          report-json: "./new-log-viewer/eslint-report.json"
